export const APP_TEAM_NAME: Record<string, string> = {
  ger: 'Germany',
  fra: 'France',
  esp: 'Spain',
  eng: 'England',
  por: 'Portugal',
  ned: 'Netherlands',
  bel: 'Belgium',
  ita: 'Italy',
  aut: 'Austria',
  sui: 'Switzerland',
  nor: 'Norway',
  swe: 'Sweden',
  hun: 'Hungary',
  sco: 'Scotland',
  cze: 'Czech Republic',
  cro: 'Croatia',
  bih: 'Bosnia and Herzegovina',
  tur: 'Turkey',
  srb: 'Serbia',
  alb: 'Albania',
  bra: 'Brazil',
  arg: 'Argentina',
  col: 'Colombia',
  par: 'Paraguay',
  uru: 'Uruguay',
  ecu: 'Ecuador',
  ven: 'Venezuela',
  usa: 'United States',
  mex: 'Mexico',
  can: 'Canada',
  pan: 'Panama',
  hai: 'Haiti',
  cuw: 'Curacao',
  crc: 'Costa Rica',
  jam: 'Jamaica',
  alg: 'Algeria',
  mar: 'Morocco',
  sen: 'Senegal',
  egy: 'Egypt',
  gha: 'Ghana',
  zaf: 'South Africa',
  cpv: 'Cape Verde',
  nga: 'Nigeria',
  cmr: 'Cameroon',
  civ: "Cote d'Ivoire",
  drc: 'DR Congo',
  gnb: 'Guinea-Bissau',
  tun: 'Tunisia',
  jpn: 'Japan',
  kor: 'South Korea',
  aus: 'Australia',
  irn: 'Iran',
  sau: 'Saudi Arabia',
  qat: 'Qatar',
  uzb: 'Uzbekistan',
  jor: 'Jordan',
  irq: 'Iraq',
  nzl: 'New Zealand',
};
